Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -18,14 +18,18 @@ jobs:
       run: |
         set -o pipefail
         mkdir -p ~/.ssh
+        # Decoding SSH Key
         echo "${{ secrets.EC2_SSH_KEY_BASE64 }}" | base64 --decode > ~/.ssh/id_rsa
+        # Ensure the key is there and readable
+        ls -la ~/.ssh
+        cat ~/.ssh/id_rsa || echo "Failed to decode key"  # Debugging output
         chmod 600 ~/.ssh/id_rsa  # Set permissions for the private key
         ssh-keyscan -H 18.206.218.236 >> ~/.ssh/known_hosts  # Add EC2 host to known hosts
 
     # Deploy to the EC2 instance
     - name: Deploy to EC2
       run: |
-        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -i ~/.ssh/id_rsa ec2-user@18.206.218.236 "
+        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@18.206.218.236 "
           sudo chown -R ec2-user:ec2-user /home/ec2-user/security-checks && \
           git config --global --add safe.directory /home/ec2-user/security-checks && \
           cd /home/ec2-user/security-checks && \
